// Code generated by github.com/99designs/gqlgen, DO NOT EDIT.

package model

import (
	"time"
)

type Message struct {
	ID        string    `json:"id"`
	Text      string    `json:"text"`
	CreatedAt time.Time `json:"createdAt"`
	User      *User     `json:"user"`
}

type Mutation struct {
}

type NewUser struct {
	DiscordID   string `json:"discordId"`
	DiscordName string `json:"discordName"`
	PictureURL  string `json:"pictureUrl"`
}

type Query struct {
}

type User struct {
	ID          string `json:"id"`
	DiscordID   string `json:"discordId"`
	PictureURL  string `json:"pictureUrl"`
	DiscordName string `json:"discordName"`
}
